# Auto-generated by compute_scales.py — do not edit manually
BATTING_SCALES = {
    "IPL": {
        "overall": {
            "avg": {
                "min": 2.79,
                "max": 55.67
            },
            "sr": {
                "min": 43.02,
                "max": 212.64
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 87.27
            },
            "dot_ball_pct": {
                "min": 22.92,
                "max": 65.52
            },
            "balls_per_bdy": {
                "min": 2.8,
                "max": 43.5
            }
        },
        "pp": {
            "avg": {
                "min": 9.57,
                "max": 98.0
            },
            "sr": {
                "min": 65.56,
                "max": 206.94
            },
            "boundary_pct": {
                "min": 33.9,
                "max": 91.28
            },
            "dot_ball_pct": {
                "min": 35.87,
                "max": 69.14
            },
            "balls_per_bdy": {
                "min": 2.53,
                "max": 18.0
            }
        },
        "middle": {
            "avg": {
                "min": 11.71,
                "max": 56.2
            },
            "sr": {
                "min": 70.44,
                "max": 198.77
            },
            "boundary_pct": {
                "min": 25.17,
                "max": 77.09
            },
            "dot_ball_pct": {
                "min": 20.99,
                "max": 53.66
            },
            "balls_per_bdy": {
                "min": 3.38,
                "max": 24.0
            }
        },
        "death": {
            "avg": {
                "min": 5.33,
                "max": 152.0
            },
            "sr": {
                "min": 89.89,
                "max": 243.42
            },
            "boundary_pct": {
                "min": 41.24,
                "max": 82.83
            },
            "dot_ball_pct": {
                "min": 8.55,
                "max": 53.93
            },
            "balls_per_bdy": {
                "min": 2.71,
                "max": 10.36
            }
        }
    },
    "SA20": {
        "overall": {
            "avg": {
                "min": 7.6,
                "max": 66.8
            },
            "sr": {
                "min": 83.53,
                "max": 171.07
            },
            "boundary_pct": {
                "min": 25.35,
                "max": 80.31
            },
            "dot_ball_pct": {
                "min": 23.6,
                "max": 49.62
            },
            "balls_per_bdy": {
                "min": 3.6,
                "max": 21.25
            }
        },
        "pp": {
            "avg": {
                "min": 13.0,
                "max": 69.5
            },
            "sr": {
                "min": 86.62,
                "max": 174.09
            },
            "boundary_pct": {
                "min": 57.51,
                "max": 82.88
            },
            "dot_ball_pct": {
                "min": 39.11,
                "max": 60.63
            },
            "balls_per_bdy": {
                "min": 3.34,
                "max": 8.68
            }
        },
        "middle": {
            "avg": {
                "min": 9.75,
                "max": 47.4
            },
            "sr": {
                "min": 86.72,
                "max": 170.67
            },
            "boundary_pct": {
                "min": 30.91,
                "max": 68.75
            },
            "dot_ball_pct": {
                "min": 23.7,
                "max": 53.66
            },
            "balls_per_bdy": {
                "min": 4.62,
                "max": 16.0
            }
        },
        "death": {
            "avg": {
                "min": 7.67,
                "max": 49.8
            },
            "sr": {
                "min": 109.18,
                "max": 227.36
            },
            "boundary_pct": {
                "min": 42.99,
                "max": 80.5
            },
            "dot_ball_pct": {
                "min": 18.35,
                "max": 46.34
            },
            "balls_per_bdy": {
                "min": 3.03,
                "max": 8.91
            }
        }
    },
    "T20I": {
        "overall": {
            "avg": {
                "min": 1.54,
                "max": 61.5
            },
            "sr": {
                "min": 16.05,
                "max": 237.08
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 89.41
            },
            "dot_ball_pct": {
                "min": 17.59,
                "max": 87.93
            },
            "balls_per_bdy": {
                "min": 2.34,
                "max": 140.0
            }
        },
        "pp": {
            "avg": {
                "min": 2.22,
                "max": 134.0
            },
            "sr": {
                "min": 21.51,
                "max": 197.85
            },
            "boundary_pct": {
                "min": 10.26,
                "max": 90.76
            },
            "dot_ball_pct": {
                "min": 31.34,
                "max": 83.87
            },
            "balls_per_bdy": {
                "min": 2.65,
                "max": 110.0
            }
        },
        "middle": {
            "avg": {
                "min": 1.4,
                "max": 102.0
            },
            "sr": {
                "min": 15.05,
                "max": 260.18
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 88.44
            },
            "dot_ball_pct": {
                "min": 19.43,
                "max": 89.25
            },
            "balls_per_bdy": {
                "min": 2.35,
                "max": 126.0
            }
        },
        "death": {
            "avg": {
                "min": 3.9,
                "max": 86.0
            },
            "sr": {
                "min": 60.49,
                "max": 241.46
            },
            "boundary_pct": {
                "min": 8.16,
                "max": 81.67
            },
            "dot_ball_pct": {
                "min": 15.13,
                "max": 63.41
            },
            "balls_per_bdy": {
                "min": 2.73,
                "max": 81.0
            }
        }
    },
    "IPL_SA20": {
        "overall": {
            "avg": {
                "min": 2.79,
                "max": 58.33
            },
            "sr": {
                "min": 43.02,
                "max": 206.56
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 87.27
            },
            "dot_ball_pct": {
                "min": 23.6,
                "max": 65.52
            },
            "balls_per_bdy": {
                "min": 2.8,
                "max": 43.5
            }
        },
        "pp": {
            "avg": {
                "min": 9.57,
                "max": 98.0
            },
            "sr": {
                "min": 65.56,
                "max": 206.94
            },
            "boundary_pct": {
                "min": 33.9,
                "max": 91.28
            },
            "dot_ball_pct": {
                "min": 35.87,
                "max": 69.14
            },
            "balls_per_bdy": {
                "min": 2.53,
                "max": 18.0
            }
        },
        "middle": {
            "avg": {
                "min": 9.55,
                "max": 81.4
            },
            "sr": {
                "min": 70.44,
                "max": 198.77
            },
            "boundary_pct": {
                "min": 25.17,
                "max": 77.09
            },
            "dot_ball_pct": {
                "min": 20.99,
                "max": 55.81
            },
            "balls_per_bdy": {
                "min": 3.38,
                "max": 24.0
            }
        },
        "death": {
            "avg": {
                "min": 5.17,
                "max": 152.0
            },
            "sr": {
                "min": 89.89,
                "max": 232.57
            },
            "boundary_pct": {
                "min": 41.24,
                "max": 82.83
            },
            "dot_ball_pct": {
                "min": 14.32,
                "max": 53.93
            },
            "balls_per_bdy": {
                "min": 2.8,
                "max": 10.36
            }
        }
    },
    "IPL_T20I": {
        "overall": {
            "avg": {
                "min": 1.54,
                "max": 61.5
            },
            "sr": {
                "min": 16.05,
                "max": 237.08
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 89.41
            },
            "dot_ball_pct": {
                "min": 17.59,
                "max": 87.93
            },
            "balls_per_bdy": {
                "min": 2.34,
                "max": 140.0
            }
        },
        "pp": {
            "avg": {
                "min": 2.22,
                "max": 134.0
            },
            "sr": {
                "min": 21.51,
                "max": 197.85
            },
            "boundary_pct": {
                "min": 10.26,
                "max": 90.76
            },
            "dot_ball_pct": {
                "min": 31.34,
                "max": 83.87
            },
            "balls_per_bdy": {
                "min": 2.65,
                "max": 110.0
            }
        },
        "middle": {
            "avg": {
                "min": 1.4,
                "max": 102.0
            },
            "sr": {
                "min": 15.05,
                "max": 260.18
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 88.44
            },
            "dot_ball_pct": {
                "min": 19.59,
                "max": 89.25
            },
            "balls_per_bdy": {
                "min": 2.35,
                "max": 126.0
            }
        },
        "death": {
            "avg": {
                "min": 3.75,
                "max": 89.5
            },
            "sr": {
                "min": 56.25,
                "max": 241.46
            },
            "boundary_pct": {
                "min": 8.16,
                "max": 80.9
            },
            "dot_ball_pct": {
                "min": 16.35,
                "max": 63.75
            },
            "balls_per_bdy": {
                "min": 2.73,
                "max": 81.0
            }
        }
    },
    "SA20_T20I": {
        "overall": {
            "avg": {
                "min": 1.54,
                "max": 61.5
            },
            "sr": {
                "min": 16.05,
                "max": 237.08
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 89.41
            },
            "dot_ball_pct": {
                "min": 17.59,
                "max": 87.93
            },
            "balls_per_bdy": {
                "min": 2.34,
                "max": 140.0
            }
        },
        "pp": {
            "avg": {
                "min": 2.22,
                "max": 134.0
            },
            "sr": {
                "min": 21.51,
                "max": 197.85
            },
            "boundary_pct": {
                "min": 10.26,
                "max": 90.76
            },
            "dot_ball_pct": {
                "min": 31.34,
                "max": 83.87
            },
            "balls_per_bdy": {
                "min": 2.65,
                "max": 110.0
            }
        },
        "middle": {
            "avg": {
                "min": 1.4,
                "max": 110.0
            },
            "sr": {
                "min": 15.05,
                "max": 260.18
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 88.44
            },
            "dot_ball_pct": {
                "min": 19.43,
                "max": 89.25
            },
            "balls_per_bdy": {
                "min": 2.35,
                "max": 126.0
            }
        },
        "death": {
            "avg": {
                "min": 3.9,
                "max": 86.0
            },
            "sr": {
                "min": 60.49,
                "max": 241.46
            },
            "boundary_pct": {
                "min": 8.16,
                "max": 81.67
            },
            "dot_ball_pct": {
                "min": 15.13,
                "max": 63.28
            },
            "balls_per_bdy": {
                "min": 2.73,
                "max": 81.0
            }
        }
    },
    "ALL": {
        "overall": {
            "avg": {
                "min": 1.54,
                "max": 61.5
            },
            "sr": {
                "min": 16.05,
                "max": 237.08
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 89.41
            },
            "dot_ball_pct": {
                "min": 17.59,
                "max": 87.93
            },
            "balls_per_bdy": {
                "min": 2.34,
                "max": 140.0
            }
        },
        "pp": {
            "avg": {
                "min": 2.22,
                "max": 134.0
            },
            "sr": {
                "min": 21.51,
                "max": 197.85
            },
            "boundary_pct": {
                "min": 10.26,
                "max": 90.76
            },
            "dot_ball_pct": {
                "min": 31.34,
                "max": 83.87
            },
            "balls_per_bdy": {
                "min": 2.65,
                "max": 110.0
            }
        },
        "middle": {
            "avg": {
                "min": 1.4,
                "max": 110.0
            },
            "sr": {
                "min": 15.05,
                "max": 260.18
            },
            "boundary_pct": {
                "min": 0.0,
                "max": 88.44
            },
            "dot_ball_pct": {
                "min": 19.59,
                "max": 89.25
            },
            "balls_per_bdy": {
                "min": 2.35,
                "max": 126.0
            }
        },
        "death": {
            "avg": {
                "min": 3.75,
                "max": 89.5
            },
            "sr": {
                "min": 56.25,
                "max": 241.46
            },
            "boundary_pct": {
                "min": 8.16,
                "max": 80.9
            },
            "dot_ball_pct": {
                "min": 16.35,
                "max": 63.75
            },
            "balls_per_bdy": {
                "min": 2.73,
                "max": 81.0
            }
        }
    }
}

# Auto-generated bowling scales
BOWLING_SCALES = {
    "IPL": {
        "overall": {
            "economy": {
                "min": 6.09,
                "max": 13.0
            },
            "avg": {
                "min": 12.09,
                "max": 136.0
            },
            "bowling_sr": {
                "min": 10.33,
                "max": 90.0
            },
            "dot_ball_pct": {
                "min": 18.52,
                "max": 55.0
            },
            "boundary_given_pct": {
                "min": 7.87,
                "max": 39.39
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 2.2
            }
        },
        "pp": {
            "economy": {
                "min": 4.0,
                "max": 11.18
            },
            "avg": {
                "min": 12.43,
                "max": 138.0
            },
            "bowling_sr": {
                "min": 11.14,
                "max": 84.0
            },
            "dot_ball_pct": {
                "min": 30.0,
                "max": 64.1
            },
            "boundary_given_pct": {
                "min": 6.41,
                "max": 34.85
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.15
            }
        },
        "middle": {
            "economy": {
                "min": 6.0,
                "max": 11.63
            },
            "avg": {
                "min": 14.12,
                "max": 167.0
            },
            "bowling_sr": {
                "min": 10.0,
                "max": 121.0
            },
            "dot_ball_pct": {
                "min": 16.67,
                "max": 50.0
            },
            "boundary_given_pct": {
                "min": 6.67,
                "max": 31.03
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.2
            }
        },
        "death": {
            "economy": {
                "min": 6.49,
                "max": 14.72
            },
            "avg": {
                "min": 6.56,
                "max": 138.0
            },
            "bowling_sr": {
                "min": 6.06,
                "max": 66.0
            },
            "dot_ball_pct": {
                "min": 14.29,
                "max": 48.75
            },
            "boundary_given_pct": {
                "min": 11.46,
                "max": 39.06
            },
            "wkts_per_innings": {
                "min": 0.14,
                "max": 1.78
            }
        }
    },
    "SA20": {
        "overall": {
            "economy": {
                "min": 4.4,
                "max": 11.35
            },
            "avg": {
                "min": 9.55,
                "max": 90.5
            },
            "bowling_sr": {
                "min": 9.71,
                "max": 51.5
            },
            "dot_ball_pct": {
                "min": 21.95,
                "max": 60.0
            },
            "boundary_given_pct": {
                "min": 6.86,
                "max": 29.9
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 2.22
            }
        },
        "pp": {
            "economy": {
                "min": 5.2,
                "max": 10.6
            },
            "avg": {
                "min": 13.71,
                "max": 125.0
            },
            "bowling_sr": {
                "min": 11.12,
                "max": 90.0
            },
            "dot_ball_pct": {
                "min": 34.85,
                "max": 56.86
            },
            "boundary_given_pct": {
                "min": 11.67,
                "max": 30.0
            },
            "wkts_per_innings": {
                "min": 0.09,
                "max": 0.92
            }
        },
        "middle": {
            "economy": {
                "min": 5.0,
                "max": 11.53
            },
            "avg": {
                "min": 9.63,
                "max": 118.0
            },
            "bowling_sr": {
                "min": 9.71,
                "max": 73.0
            },
            "dot_ball_pct": {
                "min": 22.22,
                "max": 46.21
            },
            "boundary_given_pct": {
                "min": 4.55,
                "max": 29.87
            },
            "wkts_per_innings": {
                "min": 0.1,
                "max": 1.78
            }
        },
        "death": {
            "economy": {
                "min": 6.09,
                "max": 15.42
            },
            "avg": {
                "min": 10.46,
                "max": 70.5
            },
            "bowling_sr": {
                "min": 6.73,
                "max": 34.5
            },
            "dot_ball_pct": {
                "min": 19.51,
                "max": 44.78
            },
            "boundary_given_pct": {
                "min": 13.08,
                "max": 36.92
            },
            "wkts_per_innings": {
                "min": 0.23,
                "max": 1.1
            }
        }
    },
    "T20I": {
        "overall": {
            "economy": {
                "min": 2.42,
                "max": 13.28
            },
            "avg": {
                "min": 2.64,
                "max": 233.0
            },
            "bowling_sr": {
                "min": 6.55,
                "max": 150.0
            },
            "dot_ball_pct": {
                "min": 11.29,
                "max": 66.67
            },
            "boundary_given_pct": {
                "min": 0.0,
                "max": 33.8
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 3.67
            }
        },
        "pp": {
            "economy": {
                "min": 2.58,
                "max": 12.0
            },
            "avg": {
                "min": 4.43,
                "max": 152.0
            },
            "bowling_sr": {
                "min": 8.18,
                "max": 148.0
            },
            "dot_ball_pct": {
                "min": 27.27,
                "max": 73.33
            },
            "boundary_given_pct": {
                "min": 4.17,
                "max": 34.38
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.63
            }
        },
        "middle": {
            "economy": {
                "min": 3.08,
                "max": 12.71
            },
            "avg": {
                "min": 4.55,
                "max": 215.0
            },
            "bowling_sr": {
                "min": 6.0,
                "max": 157.0
            },
            "dot_ball_pct": {
                "min": 15.28,
                "max": 67.42
            },
            "boundary_given_pct": {
                "min": 2.38,
                "max": 33.8
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 2.33
            }
        },
        "death": {
            "economy": {
                "min": 3.97,
                "max": 14.4
            },
            "avg": {
                "min": 5.18,
                "max": 138.0
            },
            "bowling_sr": {
                "min": 5.08,
                "max": 77.0
            },
            "dot_ball_pct": {
                "min": 13.33,
                "max": 58.06
            },
            "boundary_given_pct": {
                "min": 2.86,
                "max": 37.5
            },
            "wkts_per_innings": {
                "min": 0.08,
                "max": 1.7
            }
        }
    },
    "IPL_SA20": {
        "overall": {
            "economy": {
                "min": 5.94,
                "max": 12.77
            },
            "avg": {
                "min": 12.09,
                "max": 136.0
            },
            "bowling_sr": {
                "min": 9.71,
                "max": 90.0
            },
            "dot_ball_pct": {
                "min": 18.52,
                "max": 55.0
            },
            "boundary_given_pct": {
                "min": 7.87,
                "max": 35.48
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 2.2
            }
        },
        "pp": {
            "economy": {
                "min": 4.0,
                "max": 11.18
            },
            "avg": {
                "min": 12.43,
                "max": 138.0
            },
            "bowling_sr": {
                "min": 11.14,
                "max": 90.0
            },
            "dot_ball_pct": {
                "min": 30.67,
                "max": 64.1
            },
            "boundary_given_pct": {
                "min": 6.41,
                "max": 34.85
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.15
            }
        },
        "middle": {
            "economy": {
                "min": 5.81,
                "max": 11.63
            },
            "avg": {
                "min": 12.5,
                "max": 167.0
            },
            "bowling_sr": {
                "min": 10.0,
                "max": 121.0
            },
            "dot_ball_pct": {
                "min": 16.67,
                "max": 50.0
            },
            "boundary_given_pct": {
                "min": 5.0,
                "max": 31.03
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.43
            }
        },
        "death": {
            "economy": {
                "min": 6.49,
                "max": 14.72
            },
            "avg": {
                "min": 6.56,
                "max": 58.5
            },
            "bowling_sr": {
                "min": 6.06,
                "max": 39.0
            },
            "dot_ball_pct": {
                "min": 14.29,
                "max": 46.72
            },
            "boundary_given_pct": {
                "min": 7.79,
                "max": 39.06
            },
            "wkts_per_innings": {
                "min": 0.15,
                "max": 1.78
            }
        }
    },
    "IPL_T20I": {
        "overall": {
            "economy": {
                "min": 2.42,
                "max": 13.28
            },
            "avg": {
                "min": 2.64,
                "max": 233.0
            },
            "bowling_sr": {
                "min": 6.55,
                "max": 150.0
            },
            "dot_ball_pct": {
                "min": 17.02,
                "max": 66.67
            },
            "boundary_given_pct": {
                "min": 0.0,
                "max": 33.82
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 3.67
            }
        },
        "pp": {
            "economy": {
                "min": 2.58,
                "max": 12.0
            },
            "avg": {
                "min": 4.43,
                "max": 152.0
            },
            "bowling_sr": {
                "min": 8.18,
                "max": 148.0
            },
            "dot_ball_pct": {
                "min": 26.92,
                "max": 73.33
            },
            "boundary_given_pct": {
                "min": 4.17,
                "max": 33.33
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.63
            }
        },
        "middle": {
            "economy": {
                "min": 3.08,
                "max": 12.58
            },
            "avg": {
                "min": 4.55,
                "max": 215.0
            },
            "bowling_sr": {
                "min": 6.0,
                "max": 157.0
            },
            "dot_ball_pct": {
                "min": 15.15,
                "max": 67.42
            },
            "boundary_given_pct": {
                "min": 2.38,
                "max": 33.8
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 2.33
            }
        },
        "death": {
            "economy": {
                "min": 3.97,
                "max": 14.4
            },
            "avg": {
                "min": 5.18,
                "max": 138.0
            },
            "bowling_sr": {
                "min": 5.42,
                "max": 77.0
            },
            "dot_ball_pct": {
                "min": 13.16,
                "max": 58.06
            },
            "boundary_given_pct": {
                "min": 2.86,
                "max": 37.5
            },
            "wkts_per_innings": {
                "min": 0.09,
                "max": 1.7
            }
        }
    },
    "SA20_T20I": {
        "overall": {
            "economy": {
                "min": 2.42,
                "max": 13.28
            },
            "avg": {
                "min": 2.64,
                "max": 233.0
            },
            "bowling_sr": {
                "min": 6.55,
                "max": 150.0
            },
            "dot_ball_pct": {
                "min": 11.29,
                "max": 66.67
            },
            "boundary_given_pct": {
                "min": 0.0,
                "max": 33.8
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 3.67
            }
        },
        "pp": {
            "economy": {
                "min": 2.58,
                "max": 12.0
            },
            "avg": {
                "min": 4.43,
                "max": 152.0
            },
            "bowling_sr": {
                "min": 8.18,
                "max": 148.0
            },
            "dot_ball_pct": {
                "min": 27.27,
                "max": 73.33
            },
            "boundary_given_pct": {
                "min": 4.17,
                "max": 34.38
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.63
            }
        },
        "middle": {
            "economy": {
                "min": 3.08,
                "max": 12.58
            },
            "avg": {
                "min": 4.55,
                "max": 215.0
            },
            "bowling_sr": {
                "min": 6.0,
                "max": 157.0
            },
            "dot_ball_pct": {
                "min": 15.28,
                "max": 67.42
            },
            "boundary_given_pct": {
                "min": 2.38,
                "max": 33.8
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 2.33
            }
        },
        "death": {
            "economy": {
                "min": 3.97,
                "max": 12.72
            },
            "avg": {
                "min": 4.8,
                "max": 138.0
            },
            "bowling_sr": {
                "min": 5.08,
                "max": 77.0
            },
            "dot_ball_pct": {
                "min": 13.33,
                "max": 58.06
            },
            "boundary_given_pct": {
                "min": 2.86,
                "max": 32.11
            },
            "wkts_per_innings": {
                "min": 0.08,
                "max": 1.7
            }
        }
    },
    "ALL": {
        "overall": {
            "economy": {
                "min": 2.42,
                "max": 13.28
            },
            "avg": {
                "min": 2.64,
                "max": 233.0
            },
            "bowling_sr": {
                "min": 6.55,
                "max": 150.0
            },
            "dot_ball_pct": {
                "min": 17.02,
                "max": 66.67
            },
            "boundary_given_pct": {
                "min": 0.0,
                "max": 33.82
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 3.67
            }
        },
        "pp": {
            "economy": {
                "min": 2.58,
                "max": 12.0
            },
            "avg": {
                "min": 4.43,
                "max": 152.0
            },
            "bowling_sr": {
                "min": 8.18,
                "max": 148.0
            },
            "dot_ball_pct": {
                "min": 26.92,
                "max": 73.33
            },
            "boundary_given_pct": {
                "min": 4.17,
                "max": 33.33
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 1.63
            }
        },
        "middle": {
            "economy": {
                "min": 3.08,
                "max": 12.58
            },
            "avg": {
                "min": 4.55,
                "max": 215.0
            },
            "bowling_sr": {
                "min": 6.0,
                "max": 157.0
            },
            "dot_ball_pct": {
                "min": 15.15,
                "max": 67.42
            },
            "boundary_given_pct": {
                "min": 2.38,
                "max": 33.8
            },
            "wkts_per_innings": {
                "min": 0.0,
                "max": 2.33
            }
        },
        "death": {
            "economy": {
                "min": 3.97,
                "max": 13.89
            },
            "avg": {
                "min": 5.18,
                "max": 138.0
            },
            "bowling_sr": {
                "min": 5.42,
                "max": 77.0
            },
            "dot_ball_pct": {
                "min": 13.16,
                "max": 58.06
            },
            "boundary_given_pct": {
                "min": 2.86,
                "max": 34.21
            },
            "wkts_per_innings": {
                "min": 0.09,
                "max": 1.7
            }
        }
    }
}
